### ISSUE TITLE
[agent-js-cucumber] Total TestCase count is reflecting incorrectly

### ISSUE THREAD

**Issue by ghost** [reportportal/examples-js#18]
Hello @AmsterGet and Team,

I ran the sample project you have provided with the command **npm run example:simpleTestWithRetries**
And I get the **expected** below results with Total of 10 Tests, 8 passed and 2 failed:
![image](https://user-images.githubusercontent.com/50138350/132053624-23e5a5de-0f98-42b2-84b5-f470561fafaf.png)

Now i made the below minor change in the stepDef file.
When("I ask whether it's Friday yet", function() {
  this.actualAnswer = isItFriday(this.today);
  **throw new Error('Check Failed')**
});

Now I run the same command again expecting the results as -> Total 10 Tests, 5 passed and 5 failed (3 extra failures compared to above as the particular scenario has 3 examples)
But instead i get -> Total 12 Tests, 5 passed and 7 failed.
![image](https://user-images.githubusercontent.com/50138350/132054448-164d17fa-fa05-4538-892a-3bd404e9601d.png)

Example 1 - retry 3 (considered as 1 test) 
Example 2 - 1st attempt (Fail) (considered as 1 test) 
Example 2 - 2 retries (Both Fail) (considered as 1 test) 
Example 3 - 1st attempt (Fail) (considered as 1 test) 
Example 3 - 2 retries (Both Fail) (considered as 1 test) 

Hence instead of 3 tests - we get 5 here :(

Could you please guide me!!

Thanks,
Deepalee Khare

**Comment by AmsterGet** [comment]
Closed because the reporter's account has been deleted.
