### ISSUE TITLE
The cypress example does not work

### ISSUE THREAD

**Issue by CassenH** [reportportal/examples-js#23]
Not exactly sure what the issue is but it works fine with testcafe. Maybe the call to the endpoint is wrong:

```
universal-analytics [0mFinished sending tracking calls [38;5;44m+25s[0m
follow-redirects [0mredirecting to https://mywebsite.net/ui/#notfound 
```

**Comment by AmsterGet** [comment]
Hello @CassenH!
Have you specified a URL postfixed with `/api/v1` in config?

**Comment by CassenH** [comment]
Yes, that is exactly what happened. Figured it out yesterday. This has cost me a few hours of my life. Might be a good idea to add a hint for that in the readme.

**Comment by AmsterGet** [comment]
We are already has this postfix in our example's config file and in the [agent repo](https://github.com/reportportal/agent-js-cypress#cypressjson).

**Comment by AmsterGet** [comment]
But may be it make sense to write down a separate note for this.
