### ISSUE TITLE
Unable to run the example-mocha 

### ISSUE THREAD

**Issue by ankitps1807** [reportportal/examples-js#8]
I am trying to run the given sample: https://github.com/reportportal/examples-js/tree/master/example-mocha

However, I am getting the below error: 
C:\Users\AnkitS2\mocha-rp-example\example-mocha>npm test

> @ test C:\Users\AnkitS2\mocha-rp-example\example-mocha
> node main.js

npm ERR! Test failed.  See above for more details.

Could you please advise? I have passed the correct endpoints for ReportPortal, which work fine when used with Java JUnit code.

**Comment by AmsterGet** [comment]
Hi @ankitps1807 !
As I understand it, this is just a marker that some of the tests in the example failed.
You should configure mocha by yourself to log details in the console (see https://mochajs.org/api/mocha).
Please check the results of the tests performed in RP - they should be available.

**Comment by AmsterGet** [comment]
I will close this issue.
Feel free to open it again if you have any other questions on the topic.
