### ISSUE TITLE
Unable to run the example-cypress

### ISSUE THREAD

**Issue by kevinzou0214** [reportportal/examples-js#9]
I am trying to run the given sample: https://github.com/reportportal/examples-js/tree/master/example-cypress.
There is one test failed. Does this affect the results to the report portal? I specified all the options in the cypress.json. I can't see any result in the RP.

**Comment by AmsterGet** [comment]
Hi @kevinzou0214 !
Could you please provide logs?

**Comment by AmsterGet** [comment]
Closed because of no answer from requester.
Feel free to reopen it in case of any other question related to the topic.
